SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE movie;
TRUNCATE TABLE actor;
TRUNCATE TABLE rate;
TRUNCATE TABLE movie_actor;
TRUNCATE TABLE watchlist;
TRUNCATE TABLE watchlist_movies;
SET FOREIGN_KEY_CHECKS = 1;